Fetch communities from Waku
status-im/community-dapp pull request #24
Opened 2023-05-01 17:00 UTC by prichodko

Resolves https://github.com/status-im/community-dapp/issues/3

2023-05-03 23:24 UTC, felicio commented on packages/DApp/src/hooks/useCommunities.ts
> +              new Blob([community!.identity!.images.large.payload], {
`images` can be undefined, unset by user

<img width="225" alt="image" src="https://user-images.githubusercontent.com/13265126/236072323-24d3544c-e07b-4bc2-a2cf-c3196dc2ec4c.png">

2023-05-03 23:47 UTC, felicio requested changes

2023-05-03 23:47 UTC, felicio commented on packages/DApp/src/main.tsx
<img width="333" alt="image" src="https://user-images.githubusercontent.com/13265126/236073568-7c0bf339-dad1-40cd-a685-6dad26153a50.png">

2023-05-03 23:47 UTC, felicio commented on package.json
> +    "protons-runtime": "3.1.0"
⚠️ ensures single occurrence and resolve issue with decoding BigInts causing skipping of messages

2023-05-03 23:47 UTC, felicio commented on packages/DApp/package.json
> +    "dev": "NODE_OPTIONS=--openssl-legacy-provider webpack serve --mode=development --env ENV=localhost --https",
ℹ️ set localhost

2023-05-03 23:47 UTC, felicio commented on packages/DApp/src/constants/peers.ts
> +    '/dns4/node-01.ac-cn-hongkong-c.status.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAkvEZgh3KLwhLwXg95e5ojM8XykJ4Kxi2T7hk22rnA7pJC',
🚨 awaits https://github.com/status-im/community-dapp/issues/23#issuecomment-1532668176

2023-05-03 23:47 UTC, felicio commented on packages/DApp/webpack.config.cjs
> +              zlib: false,
can be removed

2023-05-03 23:47 UTC, felicio commented on packages/DApp/webpack.config.cjs
> +                    corejs: { version: '3.26' },
required for desktop app

2023-05-04 08:12 UTC, felicio commented on packages/DApp/src/main.tsx
Validate pk input, else

```
dex.js:10118 Uncaught Error: Invalid public key multibase code
 ```

2023-05-04 09:39 UTC, felicio commented on packages/DApp/webpack.config.cjs
> +                    targets: { browsers: 'chrome 77' },
todo: request QtWebEngine (browser) to be updated instead, or configure target

2023-05-04 10:07 UTC, prichodko commented on packages/DApp/src/main.tsx
fixed in https://github.com/status-im/community-dapp/pull/24/commits/268bb741972fc625772cdec1a076c4133d221a4f

2023-05-04 10:08 UTC, prichodko commented on packages/DApp/src/main.tsx
fixed by https://github.com/status-im/community-dapp/pull/24/commits/9d81f848d625636d1e6d80da82c309f3694d4d08#diff-a6530d60d177aa6bdfe7fdb99931ef15fb4961616d23ac8af22b9f1931d39ce8R222

2023-05-04 11:05 UTC, felicio commented on packages/DApp/src/main.tsx
<img width="319" alt="image" src="https://user-images.githubusercontent.com/13265126/236186592-29ef21a3-c9a1-456d-ad86-c3bc210bbb68.png">

2023-05-04 11:10 UTC, felicio commented on packages/DApp/src/components/card/CardCommunity.tsx
> +import { useEthers, getExplorerAddressLink, ChainId } from '@usedapp/core'
> can call with Chain directly, ex:
 > import { Mainnet } from '@usedapp/core'
 > Mainnet.getExplorerAddressLink('0xC7095A52C403ee3625Ce8B9ae8e2e46083b81987')
> – https://github.com/TrueFiEng/useDApp/pull/411

<img width="834" alt="image" src="https://user-images.githubusercontent.com/13265126/236187730-e817af12-b236-465f-9f57-4291ae78da77.png">

2023-05-04 11:14 UTC, felicio commented on packages/DApp/src/hooks/useCommunities.ts
> +            link: `https://join.status.im/c/${deserializedPublicKey}}`,
non-blocking: seems like current site don't support this, see https://join.status.im/c/0x029f196bbfef4fa6a5eb81dd802133a63498325445ca1af1d154b1bb4542955133

2023-05-04 11:16 UTC, felicio commented on packages/DApp/src/providers/waku/provider.tsx
>          emitSelf: true,
non-blocking: try removing

2023-05-04 11:22 UTC, felicio approved these changes
Approved. Everything but https://github.com/status-im/community-dapp/pull/24#discussion_r1184684613, I'd say is non-blocking or not strictly related to the task and could be resolved as follow-ups.

2023-05-04 11:53 UTC, felicio commented on packages/DApp/src/constants/peers.ts
> +    '/dns4/node-01.ac-cn-hongkong-c.status.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAkvEZgh3KLwhLwXg95e5ojM8XykJ4Kxi2T7hk22rnA7pJC',
increased timeout at https://github.com/status-im/community-dapp/issues/23#issuecomment-1534496637

2023-05-04 12:11 UTC, merged