[wip] featured voting
status-im/community-dapp pull request #37
Opened 2023-05-15 12:42 UTC by jkbktl

[wip]

2023-05-15 13:21 UTC, jkbktl commented on packages/DApp/src/components/card/VoteConfirmModal.tsx
> +          history.go(0)
Added reload of the page, so user can see newly proposed votings.

2023-05-15 13:23 UTC, jkbktl commented on packages/DApp/src/pages/Featured.tsx
> +import React from 'react'
Newly created page, so we can show featured communities.

2023-05-25 19:27 UTC, jkbktl commented on packages/DApp/src/components/NotificationsList.tsx
>              const parsedLog = votingContract.interface.parseLog(log)
Here is the issue with NotificationList, it accept list of notifications which can be emmited by both contracts (voting and featuredVoting), but there is currently no way how to differentiate notification item and therefore parse it by parser with correct interface. If notification item is parsed by wrong parser it throws an exception and crashes whole page.

2023-05-25 19:39 UTC, jkbktl commented
Guys, it's ready for review, please check it out when you have a bit of time. cc @osmaczko @prichodko

2023-05-31 07:45 UTC, osmaczko commented
> Guys, it's ready for review, please check it out when you have a bit of time. I cannot add you as reviewers for some reason. cc @osmaczko @prichodko

Cool! I am on it. Could you please check tests as they are failing on CI?

2023-05-31 10:39 UTC, osmaczko reviewed
Overall looks good, thanks for implementation. However, I did spot a few minor issues:

1. Once the directory vote is finalized the view is not updated

https://github.com/status-im/community-dapp/assets/33099791/c57b4d32-ec6d-494a-8a4d-1120def969c8

2. It should not be possible to vote more than once for featured community from the same account

https://github.com/status-im/community-dapp/assets/33099791/7aa45a88-5b05-492c-aa5b-2b66e8f2233a

2023-06-28 08:54 UTC, osmaczko requested changes
Thanks. It mostly works as expected, I identified few issues:

1) (blocker) Peers should be able to vote for more than one community

https://github.com/status-im/community-dapp/assets/33099791/0153d10f-b883-450d-b126-1271f15e2088

2) (blocker) "Verify Weekly featured" doesn't work for consecutive votings (works only for first voting)

https://github.com/status-im/community-dapp/assets/33099791/30bfd3bb-976d-449b-8888-fdf69747c805

3) (minor - will create a separate issue for that) directory page refreshes itself after each vote

2023-06-28 08:58 UTC, jkbktl commented
Peers can vote for more than one community, but they can't vote multiple times for one community?

2023-06-28 09:01 UTC, osmaczko commented
> Peers can vote for more than one community, but they can't vote multiple times for one community?

Yes, exactly.

2023-06-29 11:12 UTC, osmaczko approved these changes
Tested, core functionality works fine :muscle: 

I'll create separate issues for minor stuff as followup.

2023-06-29 13:02 UTC, osmaczko commented
I gave it a second try and identified one critical issue, although I don't want to block this PR any longer. We should address it in followup.

https://github.com/status-im/community-dapp/assets/33099791/649cc729-644a-4010-8e10-83e1ac69fe3e

1) The featured communities list is wrong, `From contract for portal` should not make it into the list, as it has the lowest amount of SNT. What I think happened is either `castVotes` didn't propagate all the votes to the contract or the topN calculation is done wrongly by the contract itself. I think it is rather the former because I just double checked topN calculation in contract, also it is covered with tests.

2) The button says "Finalize Weekly featured" instead of "Verify Weekly featured", this seems to be state update issue.

2023-06-29 16:31 UTC, felicio commented on packages/contracts/package.json
> +    "hardhat": "^2.16.1",
see https://github.com/NomicFoundation/hardhat/issues/3877#issuecomment-1610103284

2023-06-29 16:34 UTC, jkbktl commented
@osmaczko let's merge it then (I don't have permissions)

2023-06-29 18:07 UTC, merged